[package]
name = "sol"
version = "0.1.0"
authors = ["Ryan Chipman <ryan@ryanchipman.com>"]

[dependencies]
rand = "0.5"
rocket = "0.3.17"
rocket_codegen = "0.3.17"
rocket_contrib = { version = "0.3.17", features = ["handlebars_templates"] }
diesel = { version = "= 1.3.3", features = ["sqlite", "r2d2"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"