
- name: latest nginx installed
  apt:
    name: nginx
    state: latest

- name: latest letsencrypt installed
  apt:
    name: letsencrypt
    state: latest

- name: letsencrypt directory created
  file:
    name: /var/www/letsencrypt
    state: directory

- name: system nginx config installed
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: default nginx site removed
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: letsencrypt nginx site installed
  template:
    src: nginx-http.j2
    dest: /etc/nginx/sites-enabled/http

- name: nginx reloaded to pick up letsencrypt site
  service:
    name: nginx
    state: restarted

- name: letsencrypt certificate generated
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}

- name: dhparams generated
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  args:
    creates: /etc/nginx/dhparams.pem

- name: https site installed
  template:
    src: nginx-le.j2
    dest: /etc/nginx/sites-enabled/le

- name: nginx reloaded to pick up https site
  service:
    name: nginx
    state: restarted

- name: cron job for cert renewal installed
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && service nginx reload
