---
- hosts: sigma
  become: true

  vars:
    ansible_python_interpreter: python3
    letsencrypt_email: letsencrypt@mail.ryanchipman.com
    domain_name: dev.solsensor.com

  pre_tasks:
    - raw: apt-get install -y python-simplejson

  tasks:

    #- name: include role with common setup tasks
    #  include_role:
    #    name: common

    - name: include role for configuring nginx https reverse-proxy
      tags: [ provision ]
      include_role:
        name: https-proxy
      vars:
        proxy_port: 8000

    - name: include role for building sol from source
      tags: [ deploy ]
      include_role:
        name: sol-build

    - name: include role for running sol service
      tags: [ deploy ]
      include_role:
        name: sol-service
