
- name: systemd unit file created
  template:
    src: sol.service.j2
    dest: /etc/systemd/system/sol.service

- name: sol service restarted
  systemd:
    name: sol
    state: restarted
    daemon_reload: true
